### PR TITLE
#100 allow other password authenticator to work ZDM-530

### PR DESCRIPTION
**Pull request by weideng1**

### CODE REVIEW

**Comment by joao-r-reis** [comment]
Did you check what each driver is doing? I checked C# and it ignores the name like the proxy would with this change. I assume python is the same and java driver 3.x too due to the tests that you ran but what about java driver 4.x?

**Comment by joao-r-reis** [comment]
@absurdfarce raised a valid point that we may not want to assume things about the authenticator so we could add an additional `if` here for the particular authenticator that we're trying to support here. Authenticators at the driver level are chosen by the user but this one in zdm proxy is pretty much internal because we don't really support any configuration on it.

In the end it may just be better to do like the drivers do and assume that if it's not the dse authenticator then the plaintext one should be used. @absurdfarce what's your opinion on this?

**Comment by joao-r-reis** [comment]
Also please create a GH issue and add this item to the changelog

**Comment by weideng1** [comment]
> Also please create a GH issue and add this item to the changelog

@joao-r-reis the GH issue was created as #100 before I opened this PR.

**Comment by absurdfarce** [comment]
Mentioned in Slack, mentioning here for sake of completeness.  We've looked at the behaviour in the Python driver as well as 3.x and 4.x of the Java driver; all three follow the same basic pattern outlined by @weideng1 here.

**Comment by absurdfarce** [comment]
So the one major difference between the examples we've looked at so far is that (at least for the Python, Java 3.x and Java 4.x cases) each driver implements the authentication logic as a pluggable component.  What I've described then is the _default_ behaviour for the unmodified drivers but consumers are always free to define their own authn logic and implement a custom AuthProvider (or equivalent) to make it happen.

What we've been discussing on the zdm side isn't as pluggable.  So there is always the _potential_ for somebody to come along with a custom authenticator we can't support via the logic described above.

I don't see any obvious way around that besides supporting a pluggable authentication model in zdm as well.  But that's a different question from whether we should make the change outlined here.  This model changes us to "use the DSE authenticator if specified otherwise assume you have something that supports plaintext auth".  As a default case that doesn't seem unreasonable to me.

**Comment by joao-r-reis** [comment]
> > Also please create a GH issue and add this item to the changelog
> 
> @joao-r-reis the GH issue was created as #100 before I opened this PR.

Add it to the changelog on this PR please

**Comment by joao-r-reis** [comment]
And add `Fixes #100` to the PR description so it links and closes the GH issue automatically

**Comment by joao-r-reis** [comment]
And we should create a new milestone for an upcoming version that will have this change, if we are not sure what the version will be yet it can be created as TBD or 2.next or 2.x (and we will rename it when we decide which version it will be)

**Comment by jeromatron** [comment]
So the remaining item is just to add it to the changelog?  After that, can we merge this and it can await a next release?

**Review by joao-r-reis — APPROVED** [review]
When CI is done, feel free to merge

**Pull request merged**
